### ISSUE TITLE
nfft! and nfft_adjoint!

### ISSUE THREAD

**Issue by robertdj** [tknopp/NFFT.jl#11]
Hi,

I don't know if this is really an issue or a deliberate choice, but I notice that the `nfft!` and `nfft_adjoint!` functions modify *and* return `fHat` and `f`, respectively. 
Would it be okay if I change them so that they do not return anything?

Best,

Robert

**Comment by tknopp** [comment]
isn't this the convention for the bang to return the modified vector?

```

julia> a=[1,4,2]
3-element Array{Int64,1}:
 1
 4
 2

julia> sort!(a)
3-element Array{Int64,1}:
 1
 2
 4
```

**Comment by robertdj** [comment]
Perhaps I have misunderstood the style guide -- I'll take a closer look!

**Comment by robertdj** [comment]
You're right - sorry about that!

Another thing with `nff!` is that it requires `fHat` to consist of zeros since `convolve!` adds to each entry of `fHat`. Would it make since to `fill!(fHat, zero(T))` inside `nfft!`?
(And likewise for `nfft_adjint!`)

**Comment by tknopp** [comment]
yes absolutely. This is a bug

**Comment by robertdj** [comment]
Okay! I'll make a commit.

**Comment by tknopp** [comment]
Should we transfer this package to an Github organization so that you can directly commit? I will of course merge your PR, but it would make your life easier.

**Comment by robertdj** [comment]
I've actually never used an organization, so I'll leave that decision to you. 
My changes are part of my previous PR, so when v0.4 is released (soon) you should be able to merge.
