### ISSUE TITLE
Using ArrayViews types

### ISSUE THREAD

**Issue by robertdj** [tknopp/NFFT.jl#12]
Hi,

It would be nice to be able to use the types from the ArrayViews package in the 2D NFFT. But this requires that the types in some of the NFFT functions are changed from `Array` to `DenseArray` or `AbstractArray`. Would that be okay with you?

Best,

Robert

**Comment by tknopp** [comment]
sure, that makes sense.

**Comment by robertdj** [comment]
I've updated the type declarations. It's part of my [PR](https://github.com/tknopp/NFFT.jl/pull/10).
