### ISSUE TITLE
Thoughts on types in nfft_adjoint!

### ISSUE THREAD

**Issue by robertdj** [tknopp/NFFT.jl#15]
I would like to use `nfft_adjoint!` to modify an array through a `SubArray` from `slice`. For this purpose `DenseArray` is too restrictive and `AbstractArray` is too permissive (as it includes e.g. `LinSpace` that doesn't have a `seindex!` method).

A custom `Union{DenseArray, SubArray}` solves the problem, but I'm not sure if there's a better way -- do you have an opinion?

**Comment by tknopp** [comment]
Isn't `StridedArray` pretty much that Union that you are looking for?

Personally I would't see a large problem with just using AbstractArray even though it is a little to permissive.

**Comment by robertdj** [comment]
`StridedArray` works! I didn't even know about that type -- where did you find that?

**Comment by tknopp** [comment]
I was quite interested in the Array type hierarchy and thus read the julia issues when the current type hierarchy was implemented

**Comment by robertdj** [comment]
Now I've found some issues on the type hierarchy as well. I'll update the methods to accept `StridedArray`.
