### ISSUE TITLE
New features?

### ISSUE THREAD

**Issue by robertdj** [tknopp/NFFT.jl#16]
@tknopp I've been thinking about a couple of things that would be nice to have:

- General versions for all dimensions of functions like `apodization` and `convolve`.
- If possible, support for parallel computing with `SharedArrays` / `DistributedArrays`.
- `nfft` along dimensions, i.e., a counterpart to `fft(A, dim)`.

I've come up with a suggestion for the first part: Check out line 478 in https://github.com/robertdj/NFFT.jl/blob/master/src/NFFT.jl 
Would do you think of this approach? There's no performance degrade, but it may reduce readability of the code...

I have no experience with creating parallel Julia code yet and I don't know how well macros such as `@sync` and `@parallel` interact with the `Base.Cartesian` macros used in the above `apodization`.

**Comment by tknopp** [comment]
@robertdj: I am currently travelling and will respond once I am back.

**Comment by robertdj** [comment]
Great :-)

**Comment by tknopp** [comment]
To the generalization of the code:
- If I understand it you propose to use the Cartesian macros to make this fast. Did you have a look at #5. There was another attempt in that thread. Not sure which is better since I have no experience with the Cartesian macros
- I actually thought that with julia 0.4 it might be possible to implement this equally efficient without macros using "CartesianRange". See the blog post from Tim Holy: http://julialang.org/blog/2016/02/iteration

**Comment by tknopp** [comment]
nfft along dimensions is definitely usable. In optical coherence tomography one uses the nfft only along one direction of a Bscan.

**Comment by robertdj** [comment]
Actually, I missed <https://github.com/tknopp/NFFT.jl/pull/5>... It seems to be a similar idea, but with an older syntax. AFAIK it requires some work to view generated code. The PR provides this functionality and I dont'.
Is there any reason why the PR wasn't merged?

At first I looked into using CartesianRange with inspiration from the very same blog post, but I wasn't able to make the `apodization!`function fast: With CartesianRange the new indices computed with `rem` / `%` must be stored in an `Ntuple` or `Vector` and it is slow to create and/or use these for indexing.

**Comment by tknopp** [comment]
I have not merged it primary because it was not a pull request an there were some open issues.

In general I am fine merging such an implementation, although I might want to at least keep the explicit 1D implementation for reference. Since you have more experience with Cartesian macros I think it would be best that you decide what you can take from #5 or where your code is better. In general my very slow fallback should be removed when you have implemented fast versions for any dimension. 

Regarding CartesianRanges: How much slower is it? It might be something where we could ask Tim for help. I actually thought that `anodization!` should be a primary example where the new infrastructure would shine.

**Comment by robertdj** [comment]
I also think it's a good idea to keep at least the 1D implementation as it is easier to read. 

I ended up asking for help on [StackOverflow](http://stackoverflow.com/questions/38889303/in-julia-nfft-replace-vector-and-matrix-methods-with-a-single-array-method/) and this is where I was referrred to `Cartesian`. My first attempt can be found there.

As I recall it was an order of magnitude slower to use the `CartesianRange` approach on a 512-by-512 matrix. I started out with `apodization!` exactly because I thought it would a perfect fit for `CartesianRange`. The problem is the new indices computed with integer division, so maybe `CartesianRange` is suitable for some of the other functions.

**Comment by tknopp** [comment]
Ok fine, then lets go with `Cartesian`.

**Comment by robertdj** [comment]
In `convole!`, is there any reason why `idx2L` / `idxbL` is computed with `floor` the first one/two times, but with `round` in the innermost loop?

**Comment by tknopp** [comment]
I can't see a reason here. Maybe rerun the tests to see if there are accuracy issues (there is a test for that)

**Comment by robertdj** [comment]
The tests pass with all `floor`'s, so I'll stick with that.

**Comment by robertdj** [comment]
I've updated my fork with Cartesian versions of all functions. Let me know what you think. If you're fine with the approach I'll push to this repo as well.

**Comment by tknopp** [comment]
yes looks good

**Comment by robertdj** [comment]
Regarding the `nfft(A, dim)` I have made special methods of `apodization!` and `convolve!` that mimic the ideas from the `expfiltdim` example in the blog post above with `Rpre` & `Rpost`. 
While it looks nice, the `CartesianRange`s use **a lot** of memory. 

An easy hack would be to run the current 1D `nfft` functions on slices of the inputs. Does that sound acceptable?

**Comment by tknopp** [comment]
yes that sounds good. Its new functionality anyway so its more important to have a correct version than to have the fastest version. Tests would be appreciated when you implement that.

**Comment by robertdj** [comment]
It turned out to be difficult to slice D dimensional arrays with varying D, so I've made custom `apodization` and `convolve` methods. 
However, this also required a new type -- any remarks about that?

**Comment by tknopp** [comment]
Hm, if feasible it would of course be better to use the same plan and indicate the directional FFT as a template parameter (so that dispatching still works) 
But if that does not work having two different plans seem to be ok.

More importantly is that the high level API does not need to know about the plans and does the right thing by dispatching if an additional directional parameter is given.

**Comment by robertdj** [comment]
Having just one plan would be preferrable. But `tmpVec` needs to be a higher order array to hold the temporary results and the dimension being transformed differs from that of a `tmpVec` for a `NFFTPlan`.

I'm not sure what you mean by 'template parameter'. Is that a parameter in the type?

The high level `nfft` and `nfft!` functions work the same way for the directional plan. The directional plan (named `NFFTDirPlan` at the moment) is currently initiated with a function of the same name, but that can be changed.

**Comment by tknopp** [comment]
yes I meant type parameter. But if is there actually a difference in the plans currently? `tmpVec` seems to have the same dim and `DIM` is not really used.

**Comment by robertdj** [comment]
In an `NFFTDirPlan{D,DIM}`, `tmpVec` has the same *number* of dimensions as an `NFFTPlan{D}`. But where the size of `tmpVec` is the tuple `n` for an `NFFTPlan` the `size(p.tmpvec, DIM) = M` for an `NFFTDirPlan`.

`DIM` is also used in `convolve!` and `apodization!` for `NFFTDirPlan`'s. Check e.g. `apodization!` in my fork: <https://github.com/robertdj/NFFT.jl/blob/master/src/NFFT.jl#L427-L434>

(If my understanding of the `@generated` macro is correct): Because `DIM` is a part of the type and not a type parameter the highlighted "preexpr" section in `apodization!` is generated at compile time rather than runtime, meaning that the test `d == DIM` is not performed at runtime.

**Comment by tknopp** [comment]
yea ok, tricky. Potentially one could use `DIM==0` to be the plan for regular `nfft`and `DIM>0` for the directional `nfft`. This is possible since you can dispatch on `DIM`.

**Comment by robertdj** [comment]
That sounds interesting. If the ordinary FFT's are computed with precomputed plans it also removes the need for a separate `nfft!` method. 
Let me see if there are practical issues.

**Comment by robertdj** [comment]
One problem is that where `nfft!` for `NFFTPlan` must have a vector as the last argument, `NFFTDirPlan` must have an `D` dimensional array with `D` > 1...

**Comment by tknopp** [comment]
This is funny since `tmpVec` for `NFFTPlan` is defined to be `D` dimensional but we pass in a vector. I don't understand why this does not give an error for 2D nffts.

What can be done is to define `tmpVec` as `tmpVec::Y` and make `Y` a new type parameter. In this way one can share the type for both nfft types.

**Comment by robertdj** [comment]
I like the idea with `tmpVec::Y`. 

What method are are thinking about with the vector/`D` dim array controversy?

**Comment by tknopp** [comment]
I mean the constructor method `NFFTPlan`. It passes a vector to the type `NFFTPlan` although the later expects a `D`dimensional array.

**Comment by robertdj** [comment]
Both in the normal `NFFTPlan`, [line 67](https://github.com/robertdj/NFFT.jl/blob/master/src/NFFT.jl#L67), and the the directional `NFFTPlan`, [line 120](https://github.com/robertdj/NFFT.jl/blob/master/src/NFFT.jl#L120), the input tuple `N` of length `D` is used to initialize `tmpVec`.

**Comment by robertdj** [comment]
Perhaps there is no issue with `tmpVec` after all. If there is no type annotation for the parameters in the `nfft!` function the type/input check is performed in `consistencyCheck` and the later functions.
Let me see if I can make it work.

**Comment by tknopp** [comment]
a sorry, I misread that `n` is a tuple. Then the types are exactly the same and I do not see a reason that they cannot be reused.

**Comment by robertdj** [comment]
You are right. I've pushed a new version where the forward `nfft` works for both directional and non-directional. 
The adjoint is pretty much a copy/paste, so that will be done soon.

**Comment by robertdj** [comment]
My fork is now updated with methods for directional nfft. 

One weird thing is the tests for the directional nfft's. `nfft` along a direction should be equal to computing a 1D nfft for each vector along that direction.
For `nfft` the two results are exactly equal, but for `nfft_adjoint` they are only approximately equal. 
I can't find any bugs in the code, though (the small difference in the order of multiplication for `convolve_adjoint!` is not the explanation). 

Unless you spot any mistakes, would it be okay to tag a new release?

**Comment by tknopp** [comment]
looks good to me.
Then merge to master and tag a release.

Have you tested under 0.5 by the way? It will be released soon and it would be good if we are 0.5 ready.

**Comment by robertdj** [comment]
Great! All tests pass on 0.4, 0.5-rc4 and 0.6-dev.

**Comment by tknopp** [comment]
Perfect. Then go ahead an merge/tag. Thanks for your effort!

**Comment by robertdj** [comment]
No problem. Thanks for the discussions -- it improved the design.
