### ISSUE TITLE
Example in README does not work

### ISSUE THREAD

**Issue by giordano** [tknopp/NFFT.jl#18]
The examples in the README does not work:

```julia
julia> using NFFT

julia> M, N = 1024, 512;

julia> x = linspace(-0.4, 0.4, M);

julia> fHat = randn(M) + randn(M)*im;

julia> p = NFFTPlan(x, N)
ERROR: MethodError: no method matching NFFT.NFFTPlan{D,DIM,T}(::LinSpace{Float64}, ::Int64)
Closest candidates are:
  NFFT.NFFTPlan{D,DIM,T}(::Array{T,1}, ::Integer) at /home/mose/.julia/v0.6/NFFT/src/NFFT.jl:107
  NFFT.NFFTPlan{D,DIM,T}{D,T}(::Array{T,1}, ::Integer, ::Tuple{Vararg{Int64,D}}) at /home/mose/.julia/v0.6/NFFT/src/NFFT.jl:113
  NFFT.NFFTPlan{D,DIM,T}{D,T}(::Array{T,1}, ::Integer, ::Tuple{Vararg{Int64,D}}, ::Any) at /home/mose/.julia/v0.6/NFFT/src/NFFT.jl:113
  ...
```

Converting `x` to a `Vector` with `collect` cures the problem, but it would be useful to be able to pass `Range` objects.  This can be fixed by using abstract argument types (like `AbstractVector` in place of `Vector`, and likewise for `Matric`).  I could send pull request, I just wonder if there are reasons those methods weren't defined in this way before, and why it stopped to work at some point in the past.

Unfortunately I have to note that this package lacks completely any kind of documentation (no external manual, nor docstrings for functions), non-working example in the README don't help to start playing with it.

**Comment by robertdj** [comment]
Of course the examples in the README should work. 

It's true that `AbstractVector` also contains `LinSpace`, but to make an `NFFTPlan` type stable the saved `x` should have a concrete type and it's easier with an `Array` than an `AbstractVector`. But it can of course be collected inside the constructor -- I'll look into it. 

Adding docstrings haven't been a priority for me, personally, although I agree that it would be better to have them.

**Comment by robertdj** [comment]
It should work in the latest version: `Pkg.checkout("NFFT")` (perhaps after a `Pkg.update()`)
When a new release is tagged with the updates you can free the checkout'ed version with `Pkg.free("NFFT")`.

**Comment by giordano** [comment]
Yes, I can confirm it works now.

This is a good occasion to add a test to avoid this will be broken again in the future ;-)  In my packages I  use to add some tests drawn from examples in the README or the documentation, so that I know when I have to update or change the examples.

**Comment by robertdj** [comment]
Good point with the test.

I've added doc strings to the principal functions. Should we close this issue?

**Comment by giordano** [comment]
> Should we close this issue?

I'd have closed it, but I thought you still wanted to further looking into possible type stability issues.  If they are not there, we can close this ticket.

Thank you!
