### ISSUE TITLE
Strange crash when NFFTPlan in container

### ISSUE THREAD

**Issue by fabienbaron** [tknopp/NFFT.jl#29]
When storing NFFTPlan into a container, a crash of type "Unreachable reached" happen in Julia 0.7 and Julia 1.0. Older NFFT working with Julia 0.6 is not affected.
Code triggering the crash: https://github.com/fabienbaron/OITOOLS.jl/blob/f71842c64d1452676bfc8c358e6d3c0fbd0671d1/demos/testcrash.jl#L1-L15

**Comment by tknopp** [comment]
I can reproduce but this is pretty strange. I am not 100% sure but it might be an issue in julia itself, in which case it would probably best if you report this in the Julia repo.

**Comment by tknopp** [comment]
I have filed a bug report.

**Comment by fabienbaron** [comment]
I tried to track it with @code_native but got lost fast...
In the mean time I've put the NFFTPlan into an Array of Any rather than a structure, and this works.
