### ISSUE TITLE
usage on recovering a uniform fft?

### ISSUE THREAD

**Issue by vavrines** [tknopp/NFFT.jl#51]
Hi @tknopp 
I'm learning to use this package and maybe a noob question.
The first step I'm trying is to use non-uniform fft to recover a uniform one.

In FastTransforms.jl, I do the following
```julia
using FFTW, FastTransforms
f = [-2.0, 1.52, 0.93] # a random vector
f1 = fft(f)
x = [i/3 for i=0:2] # uniform frequency
f2 = nufft2(f .+ 0.0im, x, 1e-10)
```
and f2 is equivalent as f1.

In NFFT.jl, I tried to follow the tutorial and did as follows,
```julia
p = plan_nfft(x, 3)
adj = nfft_adjoint(p, f)
g = nfft(p, adj)
```
but the result is not equal to f1/f2.
Did I do anything the wrong way?

**Comment by JeffFessler** [comment]
adjoint is not inverse.  see #49 and
https://en.wikipedia.org/wiki/Transpose_of_a_linear_map

**Comment by vavrines** [comment]
> adjoint is not inverse. see #49 and
> https://en.wikipedia.org/wiki/Transpose_of_a_linear_map

@JeffFessler 
Thanks very much for the quick reply.
I'm not sure where the inverse get mentioned.
Is it possible here to conduct a uniform dft as `fft` does in FFTW?

**Comment by JeffFessler** [comment]
Ah, I may have have misunderstood your concern.
Definitely you can relate the NFFT to the FFT if you space the frequencies appropriately.
There are some commented out tests here:
https://github.com/JeffFessler/MIRT.jl/blob/master/test/nufft/nufft.jl
