### ISSUE TITLE
Unexpected Difference between FFT and NFFT

### ISSUE THREAD

**Issue by roflmaostc** [tknopp/NFFT.jl#61]
Hi!

It's the first (second) time trying NFFT and I'm already puzzled :smile: 

```julia
using NFFT, FFTW

function main()
    M, N = 10, 10  
    x = fftshift(fftfreq(10))
    data = randn(Float64, N)
    p = plan_nfft(x, N)
    g = nfft(p, data)
    return g, fftshift(fft(data))
end

julia> a
10-element Vector{ComplexF64}:
    -2.875849446387621 + 7.109433399925041e-17im
   -0.6283337127385992 - 1.8505031019892713im
   -1.2783925546857078 + 2.8084086304268814im
   -0.5567557156077569 - 2.418937383130122im
 -0.019876891486252452 + 1.550337129090915im
    2.8608416532162924 + 4.832460606939712e-17im
 -0.019876891486252494 - 1.550337129090915im
    -0.556755715607757 + 2.418937383130122im
   -1.2783925546857078 - 2.808408630426881im
   -0.6283337127385992 + 1.8505031019892713im

julia> b
10-element Vector{ComplexF64}:
   2.8758494344497048 + 0.0im
  -0.6283331629540757 - 1.8505036263006114im
   1.2783924393572745 - 2.8084094399161748im
   -0.556755547528122 - 2.4189381913087367im
 0.019877272680477037 - 1.5503375854166985im
    2.860841708455805 + 0.0im
 0.019877272680477037 + 1.5503375854166985im
   -0.556755547528122 + 2.4189381913087367im
   1.2783924393572745 + 2.8084094399161748im
  -0.6283331629540757 + 1.8505036263006114im
```

So apparently the output is not exactly the same but instead every second amplitude seems to have the opposite sign.

Is that expected?

Best,

Felix

**Comment by tknopp** [comment]
I enable Github discussions so that we can clarify questions there in the future: https://github.com/tknopp/NFFT.jl/discussions
Not for this one, just for the future.

**Comment by tknopp** [comment]
Definition of NFFT:
https://www-user.tu-chemnitz.de/~potts/nfft/   

Definition of FFT:
https://en.wikipedia.org/wiki/Discrete_Fourier_transform

Apperently, the DFT has a minus sign, the NDFT has not.

**Comment by roflmaostc** [comment]
Ahh, fftshifting the data before fixes it (I could have guess that :D)

```
data_nfft = nfft(p, fftshift(data))

julia> a
10-element Vector{ComplexF64}:
    -5.343610629766067 - 0.6595088341664762im
   -0.3612805024205791 - 4.753843318023331im
 -0.009849005376943332 - 0.8227901448428677im
     0.556371608598486 - 3.9536296677958314im
   -1.3459035043188146 + 0.4875770430116606im
    -4.167948505164983 - 0.6277185279310713im
   -3.5071614793153505 - 3.4415167158320887im
   -1.3384835333726146 - 4.452915182844563im
    1.0031545180170667 + 1.2056834279914725im
   0.25372452046874194 + 4.792783673001126im

julia> b
10-element Vector{ComplexF64}:
    -5.343610458583627 - 0.6595086756200799im
   -0.3612813087505314 - 4.753843412995643im
 -0.009848793445605504 - 0.8227914869916141im
    0.5563716137188791 - 3.953629400130876im
   -1.3459039074389185 + 0.4875765746755736im
    -4.167949077514379 - 0.6277187986523198im
     -3.50716218532201 - 3.441517394335329im
   -1.3384836735669579 - 4.4529154360917085im
    1.0031545529400763 + 1.2056835947821647im
   0.25372394517003394 + 4.792783804524907im
```

**Comment by tknopp** [comment]
Ah okay yes, actually the sign is correct I think, I misread that. But the fftshift is of course needed.

**Comment by roflmaostc** [comment]
Oh,

so NFFT interpretes the origin at `N \div 2 + 1` whereas fft interpretes the real space origin at `1`:

```
julia> p = plan_nfft(f, 5); nfft(p, delta)
5-element Vector{ComplexF64}:
 1.0416494959750542 + 0.0im
 1.0416494959750542 + 0.0im
 1.0416494959750542 + 0.0im
 1.0416494959750542 + 0.0im
 1.0416494959750542 + 0.0im

julia> fft(delta)
5-element Vector{ComplexF64}:
                 1.0 + 0.0im
 -0.8090169943749475 - 0.5877852522924731im
 0.30901699437494745 + 0.9510565162951535im
 0.30901699437494745 - 0.9510565162951535im
 -0.8090169943749475 + 0.5877852522924731im

julia> using FourierTools
[ Info: Precompiling FourierTools [b18b359b-aebc-45ac-a139-9c0ccbb2871e]

julia> ft(delta) # real space interpretation with center at N \div 2 + 1
5-element ShiftedArrays.CircShiftedVector{ComplexF64, Vector{ComplexF64}}:
 1.0 + 0.0im
 1.0 + 0.0im
 1.0 + 0.0im
 1.0 + 0.0im
 1.0 + 0.0im
```

**Comment by tknopp** [comment]
yes, this is much more natural anyway when working with Fourier data. Think of the continuous FT, where also everything is centered around the origin. The NDFT is linked actually more to the Fourier Series than to the DFT. You can see this as the sampling nodes are from one period of the Torus [-0.5, 0.5)

**Comment by JeffFessler** [comment]
FWIW, I went through similar tests when I first started using NFFT.jl.
https://github.com/JeffFessler/MIRT.jl/tree/main/test/nufft
I wrote (slow) DTFT functions and validated them vs FFT, then checked NFFT vs DTFT.
The tests I wrote are not well documented, but the functions they call have decent docstrings.
Just FYI.

**Comment by roflmaostc** [comment]
Yeah I agree with the center, it's just confusing since FFT doesn't do that.

Thanks a lot helping me!

**Comment by tknopp** [comment]
I think we should put some FAQ section into the documentation to make this clear. The current documentation was basically just a stub. But with the current major revision of the package structure we should also work on improving that. We can basically also look at https://nfft.github.io/NFFT3.jl/stable/ but directly taking documentation from there is not possible due to the GPL license.
